name: GFW Additional Rules
description: "添加访问受限域名"
title: "[Request] Add new restricted domains"
labels: gfwplus
body:
  - type: dropdown
    id: rule_type
    attributes:
      label: Rule Type
      options:
        - Domain (完整域名)
        - Keyword (域名关键字)
    validations:
      required: true
  - type: input
    id: content
    attributes:
      label: Content
      description: "填写域名或域名关键词，多个请用英文逗号 (,) 分隔"
      placeholder: "e.g.: `google.com, youtube.com` or `ads, tracking`"
    validations:
      required: true
