name: GFW Additional Rules
about: 添加访问受限域名
title: "[Request] Add new restricted Domain"
labels: gfwplus
body:
  - type: dropdown
    id: rule_type
    attributes:
      label: Rule Type
      options:
        - Domain (完整域名)
        - Keyword (域名关键字)
    validations:
      required: true
