name: GFW Additional Rules
about: 添加访问受限域名
title: "[Request] Add new restricted Domain"
labels: gfwplus
body:
  - type: dropdown
    id: rule_type
    attributes:
      label: 规则类型
      options:
        - Domain (完整域名)
        - Keyword (域名关键字)
    validations:
      required: true
  - type: input
    id: content
    attributes:
      label: 具体内容
      placeholder: "例如: google.com 或 ads"
    validations:
      required: true
